#!/usr/bin/env python

import psycopg2, sys
from psycopg2 import extras

connection = psycopg2.connect(dbname='expenses') 
try:
    with connection:
        with connection.cursor(cursor_factory=extras.DictCursor) as cursor:
            cursor.execute("""SELECT * FROM expenses
                          ORDER BY created_on DESC
                          """)
            all_rows = cursor.fetchall()
finally:
    connection.close()

def expense_listing(arg):
    for row in arg:
        columns = [
            str(row['id']).rjust(3),
            str(row['created_on']),
            str(row['amount']).rjust(12),
            str(row['memo'])
        ]
        
        print(' | '.join(columns))

def help_content(arg):
    arg = sys.argv 
    if len(sys.argv) == 1:
        columns1 = [
            "An expense recording system",
            "Commands:"
        ]

        print("\n\n".join(columns1))
        print("\n")
        columns2 = [
            "add AMOUNT MEMO [DATE] - record a new expense",
            "clear - delete all expenses",
            "list - list all expenses",
            "delete NUMBER - remove expense with id NUMBER",
            "search QUERY - list expenses with a matching memo field"
        ]
        print("\n".join(columns2))
    elif sys.argv[1] == 'list':
        expense_listing(all_rows)
    else:
        pass

if type(sys.argv) == list:
    help_content(sys.argv)