#!/usr/bin/env python

from textwrap import dedent
import sys

import psycopg2
from psycopg2 import extras

def list_expenses():
    connection = psycopg2.connect(dbname='expenses') 
    try:
        with connection:
            with connection.cursor(cursor_factory=extras.DictCursor) as cursor:
                cursor.execute("""SELECT * FROM expenses
                            ORDER BY created_on DESC
                            """)
                all_rows = cursor.fetchall()
    finally:
        connection.close()

    for row in all_rows:
        columns = [
            str(row['id']).rjust(3),
            str(row['created_on']),
            str(row['amount']).rjust(12),
            str(row['memo'])
        ]
        
        print(' | '.join(columns))

def display_content():
    print(dedent("""
        An expense recording system

        Commands:

        add AMOUNT MEMO - record a new expense
        clear - delete all expenses
        list - list all expenses
        delete NUMBER - remove expense with id NUMBER
        search QUERY - list expenses with a matching memo field
"""))

def main():
    command = sys.argv[1] if len(sys.argv) > 1 else None

    if command == 'list':
        list_expenses()
    else:
        display_content()

if __name__ == '__main__':
    main()
